version: "3"

vars:
  CACHE_DIR: "./.local"
  PROVIDER_NAME: "lucide"
  REPO_URL: "https://github.com/lucide-icons/lucide.git"
  ICONS_DIR: "icons"
  GENERATED_REPO_URL: "https://github.com/vanviethieuanh/lucide-templ.git"

tasks:
  default:
    cmds:
      - task: clone
      - task: pull

      - task: init
      - task: install
      - task: copy-index
      - task: gen-icons

      - task: generate
      - task: clean
      - task: build

  clone:
    internal: true
    cmds:
      - mkdir -p {{ .CACHE_DIR }}
      - echo "Cloning {{ .PROVIDER_NAME }}..."
      - git clone "{{ .REPO_URL }}" "{{ .CACHE_DIR }}/{{ .PROVIDER_NAME }}"
    status:
      - test -d "{{ .CACHE_DIR }}/{{ .PROVIDER_NAME }}/.git"

  pull:
    internal: true
    cmds:
      - echo "Pulling latest changes for {{ .PROVIDER_NAME }}..."
      - git -C "{{ .CACHE_DIR }}/{{ .PROVIDER_NAME }}" pull

  init:
    internal: true
    dir: build/{{.PROVIDER_NAME}}-templ
    cmd: go mod init github.com/vanviethieuanh/{{.PROVIDER_NAME}}_templ
    status:
      - test -f go.mod

  install:
    internal: true
    dir: build/{{.PROVIDER_NAME}}-templ
    sources:
      - go.mod
    cmd:
      for:
        - github.com/a-h/templ
      cmd: go get {{.ITEM}}

  copy-index:
    internal: true
    sources:
      - templates/icons.go
    env:
      PKG_NAME: "{{.PROVIDER_NAME}}_templ"
    cmds:
      - for: sources
        cmd: gomplate -f {{ .ITEM }} -o build/{{.PROVIDER_NAME}}-templ/$(basename {{.ITEM}})

  generate:
    internal: true
    dir: build/{{.PROVIDER_NAME}}-templ
    cmd: templ generate .

  gen-icon:
    # internal: true
    vars:
      IN: ".local/{{.PROVIDER_NAME}}/{{.ICONS_DIR}}/{{.NAME}}.svg"
      OUT: "build/{{.PROVIDER_NAME}}-templ"
      ICON_FILE:
        sh: echo "{{.NAME}}" | sed 's/-/_/g'
    env:
      ICON_NAME:
        sh: echo "{{.NAME}}" | sed -r 's/(^|-)([a-z0-9])/\U\2/g'
      SVG:
        sh: cat {{.IN}}
      PKG_NAME: "{{.PROVIDER_NAME}}_templ"
    cmds:
      - echo "{{.IN}} -> {{.OUT}}"
      - gomplate -f templates/template.txt -o {{.OUT}}/{{.ICON_FILE}}.templ

  gen-icons:
    internal: true
    vars:
      FILES:
        sh: >
          find {{ .CACHE_DIR }}/{{ .PROVIDER_NAME }}/{{.ICONS_DIR}} 
          -maxdepth 1
          -name '*.svg' | sort
    cmds:
      - for: { var: FILES }
        cmd: NAME=$(basename {{.ITEM}} .svg) go-task gen-icon

    # deps:
    #   - for: { var: FILES }
    #     task: gen-icon
    #     vars:
    #       NAME:
    #         sh: basename {{.ITEM}} .svg

  clean:
    internal: true
    cmds:
      - rm build/{{.PROVIDER_NAME}}-templ/*.templ

  build:
    internal: true
    dir: build/{{.PROVIDER_NAME}}-templ
    cmds:
      - go mod tidy
      - go build
